homeassistant: true
permit_join: true
mqtt:
  base_topic: zigbee2mqtt
  server: 'mqtt://mqtt:1883'
serial:
  port: /dev/ttyACM0
frontend:
  port: 8008
devices: devices.yaml
advanced:
    pan_id: 6754
    channel: 11
    network_key: GENERATE
  